name: Nightly Build

on:
  schedule:
    - cron: '10/10 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  WEB_IMAGE: sahil1709/fastapi-beyon-crud-web
  CELERY_IMAGE: sahil1709/fastapi-beyon-crud-celery

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cp .env.example .env
        
      - name: Run Tests
        run: |
          pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Timestamp Tag
        id: set_tag
        run: |
          echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and Tag Web Image
        id: build_web
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}"
          IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
          echo "Building web image: $IMAGE_NAME:latest and $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG .
          echo "::set-output name=web-image::$IMAGE_NAME"
          echo "::set-output name=tag::$IMAGE_TAG"

      - name: Build and Tag Celery Image
        id: build_celery
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.CELERY_IMAGE }}"
          IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
          echo "Building celery image: $IMAGE_NAME:latest and $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG .
          echo "::set-output name=celery-image::$IMAGE_NAME"
          echo "::set-output name=tag::$IMAGE_TAG"

  push_image:
    name: Push Container Image to Registry
    needs: build_and_test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Web Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}:${{ needs.build_and_test.outputs.tag }}
          push: true

      - name: Push Celery Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ env.CELERY_IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.CELERY_IMAGE }}:${{ needs.build_and_test.outputs.tag }}
          push: true

  notify_failure:
    name: Notify on Failure via Email
    needs: build_and_test
    if: ${{ needs.build_and_test.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Notification Email
        run: |
          RECIPIENT="${{ secrets.NOTIFY_EMAIL }}"
          if [ -z "$RECIPIENT" ]; then
            RECIPIENT="sgupta54@dons.usfca.edu"
          fi
          echo "Recipient email: $RECIPIENT"
          export NOTIFY_EMAIL="$RECIPIENT"
          export BUILD_REPO="${{ env.WEB_IMAGE }}"
          
          cat << 'EOF' > send_failure_email.js
          const nodemailer = require('nodemailer');
          
          async function main() {
            let transporter = nodemailer.createTransport({
              host: 'smtp.ethereal.email',
              port: 587,
              auth: {
                user: 'nickolas27@ethereal.email',
                pass: 'sBubMvmrcWCsPRdJ88'
              }
            });
            
            let info = await transporter.sendMail({
              from: '"Nightly Build" <no-reply@example.com>',
              to: process.env.NOTIFY_EMAIL,
              subject: 'Nightly Build Failed',
              text: 'The nightly build for repository ' + process.env.BUILD_REPO + ' has failed. Please review the build logs for details.'
            });
            
            console.log('Message sent: ' + info.messageId);
            console.log('Preview URL: ' + nodemailer.getTestMessageUrl(info));
          }
          
          main().catch(console.error);
          EOF
          
          npm init -y
          npm install nodemailer
          
          node send_failure_email.js
        shell: bash
